### ISSUE TITLE
Feature importance 

### ISSUE THREAD

**Issue by veeresh-dammur** [jaswinder9051998/zoofs#2]
Hi, 
Thanks for the great repo. I would like to know whether we can get the ranking of the selected features after using one of your algorithm (ex: particle swarm optimization)

**Comment by jaswinder9051998** [comment]
Hi @veeresh-dammur , all the implemented algorithms are wrapper algorithms ,i.e the model building is inherently being done by whatever modelling algorithm has been passed ( eg lightgbm, xgboost, rf). So for feature importance  it is more sensible to directly use the modelling algorithm's inbuilt feature important . 
However if you have any suggestions for any other feature importance methods, kindly continue discussion in this thread.

**Comment by veeresh-dammur** [comment]
Hi @jaswinder9051998 , Thanks for the quick reply. I got your point. thanks
