### ISSUE TITLE
Looking for integrated Harris Haw Optimization in the zoofs

### ISSUE THREAD

**Issue by hanamthang** [jaswinder9051998/zoofs#6]
**Additional context**
Harris Haw Optimization (HHO) is a novel meta-heuristic optimization algorithm released in 2019 with an increasing of applied research papers. It would be great if the team can add the HHO to the zoofs which will be potential for further testing and make the zoofs more popular. 
# #

**Comment by jaswinder9051998** [comment]
hi @hanamthang we have added an initial version of Harris Hawk to the 0.1.4 release
You can find the code snippet in the readme

Since there are a lot of variations in the implementation of Binary harris hawk across research papers, the details of the implementation in zoofs might be different over time

**Comment by hanamthang** [comment]
Wow, so fast. I don't think you will add the HHO into this version of zoofs. 

My appreciation to your work. I will give a test with the HHO to my regression problems and see how it works. 

I will have further response in case of any failure or improvement. 

Thang

**Comment by jaswinder9051998** [comment]
@hanamthang 
HHO has been added to this newly released version of v0.1.4
you can go ahead and test it out

For code reference kindly see the Readme or documentation of zoofs

**Comment by jaswinder9051998** [comment]
@hanamthang 
Also do check out and share our new feature engineering library [NitroFe](https://github.com/NITRO-AI/NitroFE)
Might help you out if your problem is time-depenent

[https://github.com/NITRO-AI/NitroFE](https://github.com/NITRO-AI/NitroFE)

**Comment by hanamthang** [comment]
That's great. I will have a look at the NitroFe :-) 

I tested the HHO for regression data (same with the GWO previously). The code worked, however is 6 -8 times longer than the GWO for the same dataset. Is there any reasons for this? Due to the HHO code, algorithm or do I miss something? 

Many thanks,
Thang

**Comment by jaswinder9051998** [comment]
@hanamthang 
If you are referring to number of iterations as longer , then yes, gwp has a more power exploration phase

**Comment by hanamthang** [comment]
I mean the computation time. For the same configuration of 50 in iteration, 50 in population, the GWO took only 7 minutes whilst the HHO consumed 1h 30 minutes. So, it is due to the hunting behavior and the algorithm itself? 

Thang

**Comment by jaswinder9051998** [comment]
@hanamthang 
That is indeed because of the algorithm.
In soft/hard besiege with dives, we are supposed to recompute fitness values for newly created Y and Z(levy walk) ,
and this new computation is costly

**Comment by jaswinder9051998** [comment]
@hanamthang 
Hey , if they isn't anything related to be done, this issue can be closed
