### ISSUE TITLE
How to run GreyWolf optimizer for multiple objective?

### ISSUE THREAD

**Issue by Abhishek-Garg-Ai** [jaswinder9051998/zoofs#8]

**Comment by jaswinder9051998** [comment]
Hi @Abhishek-Garg-Ai 
Thanks for your interest in zoofs

multi-objective optimization is itself a separate field and has specialized algos and methods.

If there are no such tools at your disposal, you can define your objective and summation of two objectives (albeit i would suggest you to stick to multi-objective optimization methodologies for your multiobjective task)
Eg. Objective = Mean Squared Error + Mean Absolute Error
